name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc

    - name: Build
      run: |
        cd example
        make

    - name: Test
      run: ./example/example

    - name: Clean
      run: |
        cd example
        make clean
